# permissions for end users to edit examplekinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-init
    app.kubernetes.io/managed-by: kustomize
  name: examplekind-editor-role
rules:
- apiGroups:
  - mygroup.muvaf.github.io
  resources:
  - examplekinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mygroup.muvaf.github.io
  resources:
  - examplekinds/status
  verbs:
  - get
