# permissions for end users to view otherexamplekinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otherexamplekind-viewer-role
rules:
- apiGroups:
  - mygroup.muvaf.github.io
  resources:
  - otherexamplekinds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mygroup.muvaf.github.io
  resources:
  - otherexamplekinds/status
  verbs:
  - get
